fix: concurrent map write
Resolves the following fatal error (as of Go 1.23 or Go 1.24):

    fatal error: concurrent map iteration and map write
    goroutine 74359 [running]:
    main.writeLog({0x747c2c, 0x6}, 0xc0001e65d0, 0xc0020fe960)
      /var/lib/gitlab-runner/builds/r3V5AUxBk/0/helsinki-systems/wp4nix/main.go:41 +0x1be
    created by main.processPkgQueue in goroutine 1
      /var/lib/gitlab-runner/builds/r3V5AUxBk/0/helsinki-systems/wp4nix/main.go:359 +0x476

See https://git.helsinki.tools/helsinki-systems/wp4nix/-/jobs/3893957#L4582.